schema_version: 1

context:
  name: azure-mgmt-recoveryservicesbackup
  version: 9.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-recoveryservicesbackup-${{ version }}.tar.gz
  sha256: 1e9fd406c0c9ee2627f5a371f012f877342f7fc6f33b2564fcd14d6f0663cd0f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1

tests:
  - python:
      imports:
        - azure.mgmt.recoveryservicesbackup
        - azure.mgmt.recoveryservicesbackup.activestamp
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Recovery Services Backup Management Client Library for Python
  license: MIT
  license_file:
    - LICENSE
    - LICENSE.txt
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
