schema_version: 1

context:
  name: azure-mgmt-recoveryservicesbackup
  version: 10.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_mgmt_recoveryservicesbackup-${{ version }}.tar.gz
  sha256: 0cac3c6b872306359bbc47501d184b700846ce548f93f9c0f6ef7d1d10b723e9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.6.0
    - azure-mgmt-core >=1.6.0
    - msrest >=0.7.1
tests:
  - python:
      imports:
        - azure.mgmt.recoveryservicesbackup
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Recovery Services Backup Management Client Library for Python
  license: MIT
  license_file:
    - LICENSE
    - LICENSE.txt
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
